services:
  - type: web
    name: horilla-crm
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn horilla_crm.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
databases:
  - name: horilla_crm_db
    plan: free
